/*
 * This source file was generated by the Gradle 'init' task
 */
package pbo;

import java.util.List;
import javax.swing.JFrame;
import java.awt.CardLayout;
import pbo.config.AppConfig;
import pbo.views.LoginPage;
import pbo.views.MahasiswaListPage;

class AppNavigation extends CardLayout {

    public AppNavigation(JFrame frame) {
        super();
        frame.setLayout(this);
        frame.add(new LoginPage(frame), "LoginPage");
        frame.add(new MahasiswaListPage(frame), "MahasiswaListPage");

        this.show(frame.getContentPane(), AppConfig.initialRoute);
    }

}

public class App {

    public void start() {
        String appName = "Simple Swing App";
        int width = 600;
        int height = 400;

        JFrame frame = new JFrame(appName);

        // components add here
        // frame.add(mahasiswaListPage);
        AppNavigation navigation = new AppNavigation(frame);
        frame.setLayout(navigation);

        frame.setSize(width, height);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        new App().start();
    }
}
